In [1]:
# Torch 잘 설치 됐는지 확일할 때 쓰는 명령어

import torch

In [2]:
# GPU 쓸수있어없어 물어보는거. 즉, NVIDIA 그래픽카드 있는지 없는지 물어보는 것
torch.cuda.is_available()

True

In [3]:
# 파이토치 버전확인

torch.__version__

'2.10.0+cu126'

In [4]:
torch.tensor(5)

tensor(5)

In [5]:
data = [1,2,3]
torch.tensor(data)

tensor([1, 2, 3])

In [6]:
import numpy as np

np_data = np.array([[1,2],[3,4]])
torch.tensor(np_data)

tensor([[1, 2],
        [3, 4]])

In [7]:
torch.from_numpy(np_data)

tensor([[1, 2],
        [3, 4]])

In [8]:
torch.arange(0,10,2)  # 일정 간격으로 데이터를 생성

tensor([0, 2, 4, 6, 8])

In [9]:
torch.linspace(0,10,3)  # 3개의 간격  끝점의 보장과 정밀한 분할 때문에

tensor([ 0.,  5., 10.])

In [10]:
# 데이터를 무작위로 생성  사이즈는 2행3열짜리

torch.randint(0,10,(2,3))

tensor([[1, 1, 1],
        [9, 4, 9]])

In [11]:
torch.rand((3,3))

tensor([[0.4337, 0.3792, 0.2814],
        [0.1462, 0.7410, 0.4432],
        [0.4236, 0.9780, 0.7862]])

In [12]:
torch.rand((128,128,3))

tensor([[[0.7418, 0.3080, 0.2853],
         [0.8893, 0.7087, 0.0243],
         [0.8130, 0.9211, 0.4741],
         ...,
         [0.1198, 0.0175, 0.8931],
         [0.5338, 0.2347, 0.5102],
         [0.5872, 0.8195, 0.7852]],

        [[0.6843, 0.2231, 0.5996],
         [0.1835, 0.4418, 0.9286],
         [0.4692, 0.9445, 0.7843],
         ...,
         [0.9717, 0.2526, 0.6505],
         [0.2343, 0.4175, 0.0719],
         [0.3081, 0.5260, 0.3482]],

        [[0.6444, 0.5631, 0.6724],
         [0.2652, 0.1909, 0.9519],
         [0.6943, 0.4948, 0.4032],
         ...,
         [0.1239, 0.8553, 0.5197],
         [0.9148, 0.9898, 0.6981],
         [0.6498, 0.1227, 0.4463]],

        ...,

        [[0.1586, 0.6212, 0.0943],
         [0.1924, 0.6639, 0.2600],
         [0.3880, 0.6995, 0.7209],
         ...,
         [0.0287, 0.4815, 0.7750],
         [0.3037, 0.1219, 0.8657],
         [0.0327, 0.5355, 0.3371]],

        [[0.6463, 0.6074, 0.1869],
         [0.8116, 0.9565, 0.5927],
         [0.

In [13]:
torch.rand((3,128,128))

tensor([[[0.6547, 0.5052, 0.9786,  ..., 0.5748, 0.0112, 0.2503],
         [0.6963, 0.8823, 0.5313,  ..., 0.6829, 0.1036, 0.4725],
         [0.2035, 0.7329, 0.2213,  ..., 0.2114, 0.9715, 0.9891],
         ...,
         [0.4558, 0.2510, 0.6932,  ..., 0.8098, 0.9732, 0.2497],
         [0.0500, 0.9598, 0.2805,  ..., 0.1948, 0.3034, 0.4027],
         [0.1939, 0.4418, 0.3488,  ..., 0.1470, 0.4497, 0.8765]],

        [[0.1415, 0.9020, 0.9076,  ..., 0.5657, 0.5427, 0.6172],
         [0.8338, 0.3762, 0.1938,  ..., 0.7225, 0.6483, 0.1034],
         [0.1387, 0.0429, 0.9812,  ..., 0.8275, 0.6927, 0.6006],
         ...,
         [0.8780, 0.6478, 0.6051,  ..., 0.0030, 0.9432, 0.8522],
         [0.2366, 0.7992, 0.7832,  ..., 0.5711, 0.9003, 0.0700],
         [0.7287, 0.1211, 0.7382,  ..., 0.6894, 0.8269, 0.5827]],

        [[0.7047, 0.3063, 0.7143,  ..., 0.2941, 0.6891, 0.0834],
         [0.8738, 0.5408, 0.2535,  ..., 0.4257, 0.5236, 0.0886],
         [0.3474, 0.0281, 0.0259,  ..., 0.1710, 0.8302, 0.

In [14]:
torch.zeros(2,3)    # 0으로 가득 채우기

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.ones(2,3)    # 1로 가득채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
torch.full((2,3) , 255)

tensor([[255, 255, 255],
        [255, 255, 255]])

In [17]:
torch.eye(5,3)   # 대각선 1로 이루어진 텐서

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
# tensor의 속성

tdata = torch.randint(0,255,(128,128))
tdata

tensor([[121,  54, 131,  ..., 190, 168, 210],
        [106, 152,   8,  ..., 121, 152, 226],
        [  0,  24,   0,  ..., 100, 164, 237],
        ...,
        [ 95,  97, 124,  ...,  17, 196, 187],
        [ 45,  30, 123,  ...,  81,  18,  28],
        [ 67,  16,  32,  ..., 239, 170,  91]])

In [19]:
tdata.shape

torch.Size([128, 128])

In [20]:
tdata.dtype

torch.int64

In [21]:
tdata.device

device(type='cpu')

In [ ]:
tdata.T  # 행과열의 위치를 바꿔준다

tensor([[121, 106,   0,  ...,  95,  45,  67],
        [ 54, 152,  24,  ...,  97,  30,  16],
        [131,   8,   0,  ..., 124, 123,  32],
        ...,
        [190, 121, 100,  ...,  17,  81, 239],
        [168, 152, 164,  ..., 196,  18, 170],
        [210, 226, 237,  ..., 187,  28,  91]])

In [23]:
tdata.to('cuda')

tensor([[121,  54, 131,  ..., 190, 168, 210],
        [106, 152,   8,  ..., 121, 152, 226],
        [  0,  24,   0,  ..., 100, 164, 237],
        ...,
        [ 95,  97, 124,  ...,  17, 196, 187],
        [ 45,  30, 123,  ...,  81,  18,  28],
        [ 67,  16,  32,  ..., 239, 170,  91]], device='cuda:0')

In [24]:
tdata = tdata.to('cuda')  # GPU에 만든 새 텐서를 다시 tdata라는 이름으로 부르겠다!

In [25]:
tdata = torch.zeros(2,3)
tdata

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [26]:
tdata + 10

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [27]:
tdata = torch.zeros(2,3)
tdata1 = torch.ones(2,3)

In [28]:
print(tdata)
print(tdata1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [29]:
tdata - tdata1

tensor([[-1., -1., -1.],
        [-1., -1., -1.]])

In [30]:
tdata*tdata1

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [31]:
mat1 = torch.tensor([[1,2,3],[4,5,6]])
mat2 = torch.tensor([[1,2],[3,4],[5,6]])

torch.matmul(mat1,mat2)

# 행렬의 곱

tensor([[22, 28],
        [49, 64]])

In [32]:
mat1*mat2  #행렬이 안맞아서 (차원이 맞아서) 오류난다

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [33]:
data = torch.zeros(128,128)
data.shape
data.dim()

2

In [34]:
data = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
data.shape


torch.Size([3, 3])

In [43]:
data

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
data[0]  # 0번째 행을 가져와라

tensor([1, 2, 3])

In [38]:
data[1]  # 1번째 행을 가져와라

tensor([4, 5, 6])

In [40]:
data[:,-1]

tensor([3, 6, 9])

In [41]:
data[:,]  # 모든행

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [42]:
data[:,0:2]   # 0과1열의 모든 행을 가져와라

tensor([[1, 2],
        [4, 5],
        [7, 8]])

In [44]:
data = torch.zeros(128,128)
data

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [ ]:
# 사람 이미지   12, 12, 64(가로크기) , 64 (세로크기)
# 그럼 이미지는 행은 12행 부터 77행 전까지 가져오고  열은 12열 부터 77열 까지
data[12:77, 12:77]

# 이걸 png파일로 바꾸기만하면 이미지 가져온다
# 이게 인덱싱, 슬라이싱 개념이다

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [47]:
data = torch.tensor([[1,2],[3,4]])

torch.sum(data)

tensor(10)

In [49]:
data

tensor([[1, 2],
        [3, 4]])

In [50]:
print(data.dtype)

torch.int64


In [51]:
data.dtype

torch.int64

In [48]:
torch.mean(data)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
#float형으로바꿔야함

In [54]:
data = data.to(torch.float16)

In [55]:
torch.mean(data)

tensor(2.5000, dtype=torch.float16)

In [57]:
torch.var(data)

tensor(1.6670, dtype=torch.float16)

In [58]:
torch.std(data)

tensor(1.2910, dtype=torch.float16)

In [59]:
data = torch.randint(0,255,(128,128))

In [60]:
# numpy로 바꾸려면

data.numpy()

array([[109, 183, 145, ..., 249, 190,  45],
       [163, 175, 136, ..., 145,  39,  64],
       [ 31,  52,  33, ..., 213, 243, 114],
       ...,
       [ 80, 163,  40, ..., 172, 154,  79],
       [ 60, 215, 165, ..., 235,  26, 123],
       [134, 139, 169, ..., 159, 135, 232]], shape=(128, 128))

In [61]:
torch.tensor(np_data)

tensor([[1, 2],
        [3, 4]])

In [63]:
data = torch.tensor([1,2,3])
data

tensor([1, 2, 3])

In [65]:
data.shape

torch.Size([3])

In [109]:
data.dim()

1

In [ ]:
data_mat = data.unsqueeze(0)   # 아주 빈번하게 쓴다  차원을 하나 늘려준다

data_mat

tensor([[1, 2, 3]])

In [69]:
data = torch.tensor([[1,2,3]])
data

tensor([[1, 2, 3]])

In [71]:
data.squeeze(0)  # 차원을 하나 제거해줌

tensor([1, 2, 3])

In [73]:
data = torch.tensor([[1,2],[3,4]])
data

tensor([[1, 2],
        [3, 4]])

In [ ]:


data.dim

<function Tensor.dim()>

In [76]:
data.dtype

torch.int64

In [79]:
# 이 매트릭스를 한 줄로 쫙 펴고 싶어 벡터로 바꿔야함

data_view = data.view(-1)
data_view

tensor([1, 2, 3, 4])

In [82]:
# GPU가 있는지 없는지 확인하는것

torch.cuda.is_available()   #CUDA 사용유무

True

In [ ]:
torch.cuda.device_count()   # 그래픽카드 개수

1

In [84]:
torch.cuda.current_device()

0

In [85]:
data = torch.tensor([1,2,3])

data

tensor([1, 2, 3])

In [86]:
data.to('cuda')   #바로 gpu로 올라간다

tensor([1, 2, 3], device='cuda:0')

In [87]:
data

tensor([1, 2, 3])

In [115]:
data = data.to('cuda')   #'cuda:1'  1번 그래픽카드에 올리겠다, 여러개 있을때

In [116]:
data

tensor([1., 2., 3.], device='cuda:0', grad_fn=<ToCopyBackward0>)

In [117]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [118]:
data1 = torch.tensor([10,20,30])

data + data1

# 같은 device에 없다고 오류남. 같은 devicced에 있어야 연산이 가능하다

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [119]:
data1 = data1.to('cuda')

In [120]:
data + data1

tensor([11., 22., 33.], device='cuda:0', grad_fn=<AddBackward0>)

In [121]:
data = torch.tensor([1.,2.,3.], requires_grad=True)

data


tensor([1., 2., 3.], requires_grad=True)

In [122]:
a = data + 1

a

tensor([2., 3., 4.], grad_fn=<AddBackward0>)

In [123]:
b = a * 2
b


tensor([4., 6., 8.], grad_fn=<MulBackward0>)

In [124]:
c = b**2
c

tensor([16., 36., 64.], grad_fn=<PowBackward0>)

In [125]:
print(a.grad)
print(b.grad)

None
None


C:\Users\user\AppData\Local\Temp\ipykernel_30756\2179822287.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:497.)
  print(a.grad)
C:\Users\user\AppData\Local\Temp\ipykernel_30756\2179822287.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tens

In [126]:
loss = c.sum()

loss.backward()

In [127]:
b.backward()
print(a)
print(a.grad)
print(b)
print(b.grad)

RuntimeError: grad can be implicitly created only for scalar outputs

# Neural Network (nn) class 

In [128]:
# 신경망 만들어보자


import torch.nn as nn

# 클래스로 만들어서 사용한다
# nn.Mudule이라는 신경망을 상속받는다

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(in_features=3, out_features=4, bias=True)
        self.fc1_act = nn.ReLU()
        self.fc2 = nn.Linear(in_features=4, out_features=3, bias=True)
        self.fc2_act = nn.ReLU()
        self.fc3 = nn.Linear(in_features=3, out_features=1)

    def forward(self,x):
        out = self.fc1(x)
        out = self.fc1_act(out)
        out = self.fc2(out)
        out = self.fc2_act(out)
        out = self.fc3(out)
        return out
    


model1 = Net()
model1

# model1은 클래스를 갖고 만든 하나의 복사본이다
# 수백개 만들수있다

# 복사본인지 아닌지 구분하기위해서 self가 붙는다




Net(
  (fc1): Linear(in_features=3, out_features=4, bias=True)
  (fc1_act): ReLU()
  (fc2): Linear(in_features=4, out_features=3, bias=True)
  (fc2_act): ReLU()
  (fc3): Linear(in_features=3, out_features=1, bias=True)
)

In [129]:



list(model1.parameters())

[Parameter containing:
 tensor([[-0.2490, -0.0461,  0.1400],
         [-0.3502,  0.1841,  0.0884],
         [-0.0198, -0.3695, -0.2194],
         [-0.5579,  0.4685, -0.0639]], requires_grad=True),
 Parameter containing:
 tensor([-0.3037, -0.5147,  0.5109, -0.2958], requires_grad=True),
 Parameter containing:
 tensor([[ 0.0459, -0.1603,  0.0624, -0.1061],
         [ 0.0318, -0.1528,  0.0473, -0.0310],
         [-0.0105, -0.2794, -0.2955,  0.2153]], requires_grad=True),
 Parameter containing:
 tensor([0.4539, 0.0063, 0.4032], requires_grad=True),
 Parameter containing:
 tensor([[ 0.1831,  0.3758, -0.0084]], requires_grad=True),
 Parameter containing:
 tensor([0.1798], requires_grad=True)]

In [130]:
# 이 모델이 학습해야하는 파라미터의 개수를 세어보면

len(list(model1.parameters()))

6

In [131]:
len(list(model1.parameters()))

6

In [ ]:
ddd